### ISSUE TITLE
Gemify!

### ISSUE THREAD

**Issue by dragonchaser** [dragonchaser/maptool#1]
**Feature:** Add gemspec etc. to build this as a rubygem.

**Comment by MittchoBaroco** [comment]
Hey, I would love to work on this, can you assign it to me?

**Comment by MittchoBaroco** [comment]
hey @dragonchaser how do you want #2 to work with the gem ? should the web frontend be integrated into the gem? I found this article http://florianhanke.com/blog/2011/02/02/running-sinatra-inside-a-gem.html looks like using Sinatra inside a gem is possible (never done it), but it might be better to coordinate this issue with #2 .

**Comment by dragonchaser** [comment]
Interesting question, haven't thought about this yet. The first idea was being able to build the cli as a gem, this should suffice for now. For serving the sinatra frontend there is #3 .

**Comment by Jeremy-Walton** [comment]
@MittchoBaroco I'm working on #2. Yeah I think sinatra can be excluded and just gemify the CLI. I'll have something in a PR within the next few days so you can see how Sinatra is set up.

**Comment by dragonchaser** [comment]
Awesomework!
