### ISSUE TITLE
Add a basic sinatra webfrontend

### ISSUE THREAD

**Issue by dragonchaser** [dragonchaser/maptool#2]
Create a basic webfrontend to serve this to the web.
The frontend should contain a small form to set the variables (with, height, borders etc.) and an preformated outputarea for copy & paste.

**Comment by Jeremy-Walton** [comment]
Hi I would like to work on this for hacktoberfest. Could you please assign it to me?

**Comment by dragonchaser** [comment]
Done :)

**Comment by Jeremy-Walton** [comment]
@dragonchaser Added a PR to Add the features requested.

**Comment by dragonchaser** [comment]
Awesome work thx!
