### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by dragonchaser** [dragonchaser/maptool#3]
Create a `Dockerfile` to serve the webfrontend from #2 .

**Comment by Deepeshac2890** [comment]
Hi is this available for hacktoberfest could you please assign it to me.

**Comment by dragonchaser** [comment]
Sure, but atm it is blocked by #2.
**Additional info:**
- I want this to be based on opensuse
- I want this to include an arm32v7 build like I am using in my autobuilds: https://github.com/dragonchaser/dockerhub-autobuild/
  (if opensuse becomes a blocker at this point debian is also fine)

**Comment by dragonchaser** [comment]
This is unblocked now. Are you still up for it @Deepeshac2890 ?

**Comment by Deepeshac2890** [comment]
Hey,
 Sure I would like to learn as I have very less exp. I want to gain exp by
working on this project.

**Comment by dragonchaser** [comment]
Go ahead :) ping me if you need help.

**Comment by Deepeshac2890** [comment]
Can you please send me the link of the issue?

**Comment by dragonchaser** [comment]
This page?

**Comment by Deepeshac2890** [comment]
Actually I am replying from Gmail so I don't have link to the issue's page
😅😅
